[package]
authors = ["Bryant Luk <code@bryantluk.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "folwup_sqlite"
publish = false
readme = "README.md"
repository = "https://github.com/bluk/readfeed"
version = "0.1.0"

[dependencies]
